---
title: "R Notebook"
output: html_notebook
---
data load
```{r}
library(dplyr)
library(data.table)
library(ggplot2)
library(ggmap)
library(RColorBrewer)
library(leaflet)
library(scales)
library(plotly)
library(rlist)
library(broom)

powerplants=read.csv('global_power_plant_database.csv')

powerplants[is.na(powerplants)] = 0
powerplantsCountry = powerplants %>% filter(country_long == "United States of America")
```
Data prep
```{r}
powerplantsCountryFuel = powerplantsCountry %>% group_by(primary_fuel) 

powerplantsCountryFuelYear = powerplantsCountryFuel %>% summarise(energy2013 = 0.5* (sum(generation_gwh_2013) + sum(estimated_generation_gwh_2013)),
          energy2014 = 0.5* (sum(generation_gwh_2014) + sum(estimated_generation_gwh_2014)),
          energy2015 = 0.5* (sum(generation_gwh_2015) + sum(estimated_generation_gwh_2015)),
          energy2016 = 0.5* (sum(generation_gwh_2016) + sum(estimated_generation_gwh_2016)),
          energy2017 = 0.5* (sum(generation_gwh_2017) + sum(estimated_generation_gwh_2017)),
          )

powerplantsCountryFuelYearDF = as.data.frame(powerplantsCountryFuelYear)
powerplantsCountryFuelYearLabeled = powerplantsCountryFuelYearDF[,-1]
row.names(powerplantsCountryFuelYearLabeled) = powerplantsCountryFuelYearDF[,1]
transposePowerplantsCountryFuelYear = transpose(powerplantsCountryFuelYearLabeled)
colnames(transposePowerplantsCountryFuelYear) = powerplantsCountryFuelYearDF[,1]
transposePowerplantsCountryFuelYear$Year = c(2013,2014,2015,2016,2017)


totalEnergy = powerplantsCountryFuelYear %>% mutate(total = energy2013+ energy2014 +energy2015 + energy2016 + energy2017)

```

map
```{r}
powertype = "Wind"
leaflet(powerplants %>% filter(primary_fuel == powertype)) %>% addTiles() %>% addMarkers(~longitude,~latitude,popup= ~primary_fuel,label= ~name)
```

Total energy bar chart
```{r}
totalEnergyChart=ggplot(totalEnergy,aes(x=reorder(primary_fuel,total),y=total,fill=primary_fuel)) + geom_bar(stat="identity") + coord_flip() + scale_y_continuous(trans= 'log10', labels = trans_format('log10',math_format(10^.x))) + theme(axis.text.x = element_text(angle=90)) + ylab("Energy Accumulated MWH") + xlab("Primary Fuel")
totalEnergyChart
```

energy produced
```{r}

data_long = melt(transposePowerplantsCountryFuelYear, id="Year")
colnames(data_long) = c("Year","primary_fuel","energy")

lineplot = ggplot(data_long, aes(x=Year,y=energy, color= primary_fuel)) + ylab("Energy Produced MWH") + xlab("Year") + geom_line() + scale_y_continuous(trans= 'log10', labels = trans_format('log10',math_format(10^.x))) +ggtitle("Energy Produced over the Years per Type")

ggplotly(lineplot)
```

number of plants by type
```{r}
numberOfPlants = powerplantsCountryFuel %>% summarize(number = n())
ggplot(numberOfPlants,aes(x=reorder(primary_fuel,number), y=number,fill=primary_fuel)) + geom_bar(stat="identity") + theme(axis.text.x = element_text(angle=90)) + coord_flip() + scale_y_continuous(trans= 'log10', labels = trans_format('log10',math_format(10^.x))) + xlab("Primary Fuel") + ylab("Number of Plants") +ggtitle("Number of Plants per Type")
```

```{r}
powerplantsCountryFuelAndNumber = merge(totalEnergy,numberOfPlants,"primary_fuel","primary_fuel")
powerplantsCountryFuelAndNumber = powerplantsCountryFuelAndNumber %>% mutate(EnergyPerPlant = total/number)

totalEnergyPerPlantChart=ggplot(powerplantsCountryFuelAndNumber,aes(x=reorder(primary_fuel,EnergyPerPlant),y=EnergyPerPlant,fill=primary_fuel)) + geom_bar(stat="identity") + coord_flip() + scale_y_continuous(trans= 'log10', labels = trans_format('log10',math_format(10^.x))) + theme(axis.text.x = element_text(angle=90)) + ylab("Average Energy Accumulated MWH per Plant") + xlab("Primary Fuel")
totalEnergyPerPlantChart
```

```{r}
powerplantsCountryFuelTotal = powerplantsCountryFuel %>%
  mutate(totalEnergy = 0.5 * (
    generation_gwh_2013 + estimated_generation_gwh_2013 +
    generation_gwh_2014 + estimated_generation_gwh_2014 +
    generation_gwh_2015 + estimated_generation_gwh_2015 +
    generation_gwh_2016 + estimated_generation_gwh_2016 +
    generation_gwh_2017 + estimated_generation_gwh_2017
    ))
totalEnergyBoxPlot = ggplot(powerplantsCountryFuelTotal,aes(x=reorder(primary_fuel,totalEnergy),y=totalEnergy,fill=primary_fuel)) + geom_boxplot(show.legend = FALSE) + coord_flip() + scale_y_continuous(trans= 'log10', labels = trans_format('log10',math_format(10^.x))) + theme(axis.text.x = element_text(angle=90)) + ylab("Average Energy Accumulated MWH per Plant") + xlab("Primary Fuel")
totalEnergyBoxPlot
```
```{r}
windPowerplants = powerplantsCountryFuelTotal %>% filter(primary_fuel == "Wind")
oilPowerplants = powerplantsCountryFuelTotal %>% filter(primary_fuel == "Oil")

# Compute the analysis of variance
res.aov <- aov(totalEnergy ~ primary_fuel, data = powerplantsCountryFuelTotal)
# Summary of the analysis
summary(res.aov)
```
```{r}
thsd = TukeyHSD(res.aov, "primary_fuel", ordered = TRUE)
tidy(thsd) %>% filter(contrast=="Wind-Oil")
```